## Exercise

Load the earthquake data. It has two categories (serious event, and normal) whether the movement resulted in an earthquake over 5 degrees in the Richter scale. The first column is the category (0/1).

More information about the data set her: http://timeseriesclassification.com/description.php?Dataset=Earthquakes

#### Your task:

- Extract features and apply
    - A supervised learning algorithm (meaning using the labels).
    - An **unsupervised** learning algorithm. Here the goal is to be able to identify the structure without knowing the classes.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/Earthquakes/Earthquakes_TRAIN.txt", header = None)

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,503,504,505,506,507,508,509,510,511,512
0,1,-0.51801,-0.51801,2.65420,-0.51801,-0.51801,-0.51801,-0.51801,1.45620,2.55840,...,-0.51801,-0.51801,-0.51801,-0.51801,-0.51801,-0.51801,-0.51801,-0.51801,1.46580,-0.51801
1,0,1.94370,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,...,2.45780,3.36560,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311,-0.35311
2,0,2.63850,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,...,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610,-0.31610
3,0,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,...,1.36690,-0.53114,2.14740,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114,-0.53114
4,1,-0.59366,2.02010,1.17470,-0.59366,-0.59366,1.60600,1.21790,1.58880,-0.59366,...,1.22650,-0.59366,-0.59366,-0.59366,1.49390,-0.59366,-0.59366,-0.59366,1.89930,-0.59366